- platform: ping
  host: 192.168.1.3
  count: 2
  name: 'ping_xiaomi_hub'
  scan_interval: 60
- platform: ping
  host: 192.168.1.3
  count: 2
  name: 'ping_echo_dot'
  scan_interval: 60
- platform: ping
  host: 192.168.1.7
  count: 2
  name: 'ping_nergal'
  scan_interval: 60
- platform: ping
  host: 192.168.1.8
  count: 2
  name: 'ping_notebook'
  scan_interval: 60
- platform: ping
  host: 192.168.1.186
  count: 2
  name: 'ping_tv'
  scan_interval: 60
- platform: ping
  host: 192.168.1.6
  count: 2
  name: 'ping_chromecast_audio'
  scan_interval: 60
#####Yeelight
- platform: ping
  host: 192.168.1.10
  count: 2
  name: 'ping_yeelight_moon'
  scan_interval: 60
- platform: ping
  host: 192.168.1.63
  count: 2
  name: 'ping_yeelight_viktoriia_lamp'
  scan_interval: 60
- platform: ping
  host: 192.168.1.16
  count: 2
  name: 'ping_yeelight_master_lamp'
  scan_interval: 60
- platform: ping
  host: 192.168.1.108
  count: 2
  name: 'ping_yeelight_window'
  scan_interval: 60
- platform: ping
  host: 192.168.1.52
  count: 2
  name: 'ping_yeelight_kitchen'
  scan_interval: 60
#####Broadlink
- platform: ping
  host: 192.168.1.20
  count: 2
  name: 'ping_kitchen_fan'
  scan_interval: 60
- platform: ping
  host: 192.168.1.24
  count: 2
  name: 'ping_root_socket'
- platform: ping
  host: 192.168.1.23
  count: 2
  name: 'ping_pc_switch'
  scan_interval: 60
- platform: ping
  host: 192.168.1.25
  count: 2
  name: 'ping_beok'
  scan_interval: 60





#  Switch
#  192.168.1.14	FCECDABF568F



#  DESKTOP-U6MMARC
#  192.168.1.60	0CEEE680F0EC
#  *
#  192.168.1.142	7811DC92B037
#  Google-Nest-Mini
#  192.168.1.163	D4F547289C33
#  QCA4002
#  192.168.1.173	7C1C4ECC30D0
#  Door
#  192.168.1.185	EC71DB9D0565
#  Google-Nest-Hub
#  192.168.1.216	1CF29A5DD89A
#  OnePlus6
#  192.168.1.223	C0EEFBCAD99F
