#Автоматичне ввімкнення/вимкнення лед підсвітки разом із світильником
- alias: wall_switch_and_led_on
  trigger:
    platform: state
    entity_id: switch.wall_switch_right_158d00019f6738
    to: 'on'
    from: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_ambilight
- alias: wall_switch_and_led_off
  trigger:
    platform: state
    entity_id: switch.wall_switch_right_158d00019f6738
    to: 'off'
    from: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_ambilight

#Ранкове провітрювання
- alias: kitchen_morning_airing
  trigger:
    - platform: time
      at: '10:30:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_fan
    - delay: '01:00:00'
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_fan
#Вечірнє провітрювання
- alias: kitchen_night_airing
  trigger:
    - platform: time
      at: '18:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_fan
    - delay: '01:00:00'
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_fan

#Увімкнути провітрення на годину якщо є рух
- alias: kitchen_motion_airing
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002b4745b
    to: 'on'
  condition:
    - condition: state
      entity_id: switch.broadlink_kitchen_fan
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_fan
    - delay: '01:00:00'
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_fan

#Увімкнути led підсвітку та ялинку після заходу сонця якщо є рух
- alias: motion_led_and_christmas_tree
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002b4745b
    to: 'on'
  condition:
    - condition: sun
      after: sunset
    - condition: time
      before: '00:00:00'
    - condition: state
      entity_id: switch.broadlink_christmas_tree
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.window
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_christmas_tree
    - delay: '40:00:00'
    - service: light.turn_off
      data:
        entity_id: light.window
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_christmas_tree

#Вимкнути led підсвітку та ялинку опівночі
- alias: led_off_on_midnight
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.window
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_christmas_tree
