#Фікс для світла в кімнаті
- alias: room_light_fix
  trigger:
    platform: state
    entity_id: switch.wall_switch_left_158d0001dc2c2e
    to: 'off'
    from: 'on'
  action:
    - delay: 1
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0001dc2c2e

# Перезавантаження світильника якщо він завис
- alias: room_moon_reboot
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.room_moon
      to: 'unavailable'
      for:
        minutes: 5
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0001dc2c2e
    - delay: 1
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d0001dc2c2e

