####### 5 - Системні сценарії
###############################################################################
#
#Вимкнути broadlink_PC одразу після вмикання
- alias: broadlink_PC_off_fix
  trigger:
    platform: state
    entity_id: switch.broadlink_pc
    to: 'on'
    from: 'off'
  action:
    - delay: 1
    - service: switch.turn_off
      entity_id: switch.broadlink_pc

#Вимкнути Wake on Lan одразу після вмикання
- alias: wake_on_lan_fix
  trigger:
    platform: state
    entity_id: switch.wol
    to: 'on'
    from: 'off'
  action:
    - delay: 1
    - service: switch.turn_off
      entity_id: switch.wol

#Фікс для світла в кімнаті
- alias: room_light_fix
  trigger:
    platform: state
    entity_id: switch.wall_switch_left_158d0001dc2c2e
    to: 'off'
    from: 'on'
  action:
    - delay: 1
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0001dc2c2e

#Автоматичне вимкнення світла вночі
- alias: off_alls_witches
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: switch.turn_off
      entity_id: group.group_switches


#############
#############
#############
#############
####### ТЕСТИ
###############################################################################
#
#hub ringtone
#{
#  "gw_mac": "7811DCFAF643",
#  "ringtone_id": 29,
#  "ringtone_vol": 8
#}
#- alias: "Night Light Routine"
#  trigger:
#    platform: state
#    entity_id: switch.wall_switch_right_158d0001dc2c2e
#    to: 'on'
#    from: 'off'
#
#  action:
#    - service: xiaomi_aqara.play_ringtone
#      data:
#        gw_mac: 7811DCFAF643
#        ringtone_id: 1001
#        ringtone_vol: 8
#----Тести--#
#- alias: sunset
#  trigger:
#    platform: sun
#    event: sunset
#  action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.wall_switch_left_158d0001dc2c2e
