- alias: turn_off_all_switches
  trigger:
    - platform: time
      at: '02:00:00'
  action:
    - service: switch.turn_off
      entity_id: group.group_switches
# restart HA to keep it fresh
- alias: Restart HA
  trigger:
    platform: time
    at: "01:00:00"
  action:
    - service: homeassistant.restart
