- id: startup_notification
  alias: startup_notification
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 30
    - service: notify.telegram_notifer
      data:
        title: "⚡⚡ Увага! "
        message: "Завантажився Raspberry Pi"
    - service: media_player.volume_set
      data:
        entity_id: media_player.room
        volume_level: '0.4'
    - service: tts.google_translate_say
      entity_id: media_player.room
      data:
        message: 'Домашній сервер завантажився!'

- id: total_for_day
  alias: total_for_day
  trigger:
    - platform: time
      at: "23:59:00"
  action:
    - service: notify.telegram_notifer
      data:
        title: "Статистика використання:"
        message: "
          🖥️ PC - {{ state_attr('sensor.total_time_nergal', 'value') }}
          💻 Macbook - {{ state_attr('sensor.total_time_macbook', 'value') }}
          📺 TV - {{ state_attr('sensor.total_time_tv', 'value') }}"


- alias: WIFI_Skochko
  trigger:
    - platform: state
      entity_id: sensor.pixel_5_wifi_connection
  action:
    - service: notify.telegram_notifer
      data:
        title: "👨 WIFI Вася:"
        message: "{{ states('sensor.pixel_5_wifi_connection') }} "


- alias: WIFI_Viktorria
  trigger:
    - platform: state
      entity_id: sensor.oneplus_a6000_wifi_connection
  action:
    - service: notify.telegram_notifer
      data:
        title: "👧 WIFI Віка:"
        message: "{{ states('sensor.oneplus_a6000_wifi_connection') }} "
