homeassistant:
  name: Mothership
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 302
  unit_system: metric
  time_zone: Europe/Kiev
  packages: !include_dir_named integrations
  customize: !include customize.yaml
default_config:

## Includes
zone: !include zones.yaml
yeelight: !include yeelight.yaml
group: !include groups/groups.yaml
light: !include groups/lights.yaml
automation: !include_dir_merge_list includes/automation
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/binary-sensors


ble_monitor:
  hci_interface: 0
  discovery: True
  active_scan: False
  report_unknown: False
  batt_entities: False
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: 'A4:C1:38:EF:BF:1D'
      name: 'Livingroom'
      temperature_unit: C
