homeassistant:
  name: Mothership
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 302
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml

default_config:
frontend:
  themes: !include_dir_merge_named themes
counter: !include includes/counter.yaml
automation: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensors
script: !include_dir_merge_named includes/scripts
group: !include_dir_merge_named groups
switch: !include switch.yaml
zone: !include zones.yaml
yeelight: !include yeelight.yaml
lovelace:
  mode: yaml

plex:
  token: !secret plex_token

  #media_player:
  # Use the Python ADB implementation without authentication
#  - platform: androidtv
#    host: 192.168.1.186
#    name: android-tv
#    adb_server_ip: 127.0.0.1
#    adb_server_port: 5037

discovery:
  ignore:
    - yeelight

cast:
  media_player:
    - host: 192.168.1.6
    - host: 192.168.1.5

camera:
  - platform: generic
    still_image_url: !secret camera_still_image_url
    stream_source: !secret camera_stream_source

# Text to speech
tts:
  - platform: google_translate

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

duckdns:
  domain: !secret duckdns_url
  access_token: !secret duckdns_token

weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

#googlehome:
#  devices:
#    - host:  192.168.1.5
#    - host:  192.168.1.179
#device_tracker:
#  - platform: padavan_tracker
#    consider_home: 10
#    interval_seconds: 3
#    url: http://192.168.1.1/
#    username: !secret padavan_tracker_user
#    password: !secret padavan_tracker_password

http:
  base_url: !secret base_url

binary_sensor:
  - platform: ping
    host: 192.168.1.7


telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram_notifer
    platform: telegram
    chat_id: !secret telegram_chat_id

mobile_app:

person:
  - name: Vasyl
    id: vasyl_skochko
    user_id: 5a5730a0131749a1b1b92c150c8fc5b3
    device_trackers:
      - device_tracker.oneplus_a3010
  - name: Viktoriia
    id: viktoriia_skochko
    device_trackers:
      - device_tracker.oneplus_a6000
