homeassistant:
  # Name of the location where Home Assistant is running
  name: Mothership
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 302
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Kiev
  # Customization file
  customize: !include customize.yaml

discovery:
  ignore:
    - yeelight

plex:
  token: !secret plex_token

camera:
  - platform: generic
    still_image_url: !secret camera_still_image_url
    stream_source: !secret camera_stream_source

sun:

frontend: !include frontend.yaml

counter: !include includes/counter.yaml

automation: !include_dir_merge_list includes/automation

sensor: !include_dir_merge_list includes/sensors

script: !include_dir_merge_named includes/scripts

group: !include groups.yaml

tts:
  - platform: google_translate

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

duckdns:
  domain: !secret duckdns_url
  access_token: !secret duckdns_token

weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

lovelace:
  mode: yaml


switch: !include switch.yaml

yeelight:
  devices:
    192.168.1.108:
      name: window
    192.168.1.63:
      name: viktoriia-lamp
    192.168.1.16:
      name: master-lamp
    192.168.1.10:
      name: master-lamp

googlehome:
  devices:
    - host:  192.168.1.5
    - host:  192.168.1.179

cast:
  media_player:
    - host: 192.168.1.6
    - host: 192.168.1.5

media_player:
  # Use the Python ADB implementation without authentication
  - platform: androidtv
    name: Android TV
    host: 192.168.1.185
#device_tracker:
#  - platform: padavan_tracker
#    consider_home: 10
#    interval_seconds: 3
#    url: http://192.168.1.1/ # web interface url (don't forget about `/` in the end)
#    username: !secret padavan_tracker_user # Web interface user name
#    password: !secret padavan_tracker_password # Web interface user pass
