#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################
homeassistant:
  name: Mothership
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 302
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml
default_config:

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################
script: !include scripts.yaml
group: !include groups/all-groups.yaml
light: !include groups/lights.yaml
automation: !include_dir_merge_list includes/automation
scene: !include scenes.yaml
switch: !include switch.yaml
sensor: !include_dir_merge_list includes/sensors
zone: !include zones.yaml
yeelight: !include yeelight.yaml

#################################################################
#                                                               #
#                        Customizations                         #
#                                                               #
#################################################################
lovelace:
  mode: yaml

tts:
  - platform: google_translate

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_aqara_key

duckdns:
  domain: !secret duckdns_url
  access_token: !secret duckdns_token

http:
  base_url: !secret base_url

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram_notifer
    platform: telegram
    chat_id: !secret telegram_chat_id

camera:
  - platform: generic
    still_image_url: !secret camera_still_image_url
    stream_source: !secret camera_stream_source

weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

speedtestdotnet:
  scan_interval:
    minutes: 300
  monitored_conditions:
    - ping
    - download
    - upload

person:
  - name: Skochko
    id: skochko
    device_trackers:
      - device_tracker.oneplus_a3010
  - name: Viktoriia
    id: viktoriia
    device_trackers:
      - device_tracker.oneplus_a6000

binary_sensor:
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]
  - platform: ping
    host: 192.168.1.7
    count: 2
    name: 'Nergal'
    scan_interval: 60
  - platform: ping
    host: 192.168.1.8
    count: 2
    name: 'Notebook'
    scan_interval: 60

device_tracker:
  - platform: ping
    hosts:
      nergal: 192.168.1.7
frontend:
  themes: !include_dir_merge_named themes

climate:
  platform: floureon
  name: beok
  mac: 34:EA:34:7A:69:94
  host: 192.168.1.25
  use_external_temp: false

recorder:
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.nextsunrise
      - sensor.nextsunset
      - weather.mothership
