#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################
homeassistant:
  name: Mothership
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 302
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml
default_config:
# Text to speech
tts:
  - platform: google_translate

lovelace:
  mode: yaml
####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################
zone: !include zones.yaml
yeelight: !include yeelight.yaml
group: !include groups/groups.yaml
light: !include groups/lights.yaml

automation: !include_dir_merge_list includes/automation
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/binary-sensors

switch:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram_notifer
    platform: telegram
    chat_id: !secret telegram_chat_id

camera:
  - platform: generic
    still_image_url: !secret camera_still_image_url
    stream_source: !secret camera_stream_source

weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload



xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key


climate:
  platform: floureon
  name: beok
  mac: 34:EA:34:7A:69:94
  host: 192.168.1.25
  use_external_temp: false
