homeassistant:
  # Name of the location where Home Assistant is running
  name: Mothership
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 302
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Kiev
  # Customization file
  customize: !include customize.yaml

#test git pull plugin
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

media_player:
  # Use the Python ADB implementation without authentication
  - platform: androidtv
    name: Android TV
    host: 192.168.1.185

discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.1.108:
      name: window
    192.168.1.63:
      name: viktoriia-lamp
    192.168.1.16:
      name: master-lamp
    192.168.1.10:
      name: master-lamp
#googlehome:
#  devices:
#    - host:  192.168.1.5
#    - host:  192.168.1.179

cast:
  media_player:
    - host: 192.168.1.6
    - host: 192.168.1.5
plex:
  token: !secret plex_token

stream:

camera:
  - platform: generic
    still_image_url: !secret camera_still_image_url
    stream_source: !secret camera_stream_source

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Example configuration.yaml entry
sun:

frontend: !include frontend.yaml

counter: !include includes/counter.yaml

automation: !include_dir_merge_list includes/automation

sensor: !include_dir_merge_list includes/sensors

script: !include_dir_merge_named includes/scripts

group: !include_dir_merge_named groups/


# Text to speech
tts:
  - platform: google_translate

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

duckdns:
  domain: !secret duckdns_url
  access_token: !secret duckdns_token

weather:
  - platform: darksky
    api_key: !secret darksky_token
    mode: daily

lovelace:
  mode: yaml

# Example configuration.yaml entry
switch:
  - platform: wake_on_lan
    mac_address: "B42E99361BB8"
    name: 'wol'
    host: 192.168.1.7
  - platform: broadlink
    host: 192.168.1.20
    mac: '780F7761D452'
    type:  sp2
    friendly_name: 'broadlink_kitchen_fan'
  - platform: broadlink
    host: 192.168.1.21
    mac: '780F7717520D'
    type:  sp2
    friendly_name: 'broadlink_kitchen_ambilight'
  - platform: broadlink
    host: 192.168.1.22
    mac: '780F7717655A'
    type:  sp2
    friendly_name: 'broadlink_christmass_tree'
  - platform: broadlink
    host: 192.168.1.23
    mac: '34ea34bd5fc2'
    type:  sp2
    timeout: 10
    friendly_name: 'broadlink_PC'
  - platform: broadlink
    host: 192.168.1.24
    mac: '34ea34852721'
    type:  mp1
    friendly_name: 'broadlink_root_socket'
    slots:
      slot_1: 'one_plus3t'
      slot_2: 'google_home'
      slot_3: 'Led'
      slot_4: 'one_plus6'

#device_tracker:
#  - platform: padavan_tracker
#    consider_home: 10
#    interval_seconds: 3
#    url: http://192.168.1.1/ # web interface url (don't forget about `/` in the end)
#    username: !secret padavan_tracker_user # Web interface user name
#    password: !secret padavan_tracker_password # Web interface user pass

