- platform: broadlink
  #  host: 192.168.1.20
  mac: '780F7761D452'
  friendly_name: 'broadlink_kitchen_fan'
- platform: broadlink
  #  host: 192.168.1.21
  mac: '780F7717520D'
  friendly_name: 'broadlink_room_ambilight'
#  - platform: broadlink
#    host: 192.168.1.22
#    mac: '780F7717655A'
#    type:  sp2
#    friendly_name: 'broadlink_christmas_tree'
- platform: broadlink
  #    host: 192.168.1.23
  mac: '34ea34bd5fc2'
  timeout: 10
  friendly_name: 'broadlink_pc'
- platform: broadlink
  #   host: 192.168.1.24
  mac: '34ea34852721'
  friendly_name: 'broadlink_root_socket'

- platform: wake_on_lan
  mac: 'B4-2E-99-36-1B-B8'
