title: Mothership
# Include external resources
resources:
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /local/style.css
    type: css
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /local/radio-selector.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/gui-sandbox.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
background: var(--background-image)
# Exclude entities from "Unused entities" view
excluded_entities:
views:
  ### головний екран  ############
  - title:
    icon: mdi:home-account
    path: home
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - sensor.skochko
                  - type: divider
                  - sensor.battery_skochko

              - type: entities
                show_header_toggle: false
                entities:
                  - sensor.viktoriia
                  - type: divider
                  - sensor.battery_viktoriia
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Вологість
            entities:
              - sensor.humidity_158d0002437932
            line_color: '#1976d2'
            line_width: 4
            font_size: 40
            show:
              labels: true
          - type: custom:mini-graph-card
            name: Освітлення
            entities:
              - sensor.illumination_158d0002b4745b
            line_color: '#ffb300'
            line_width: 4
            font_size: 40
            show:
              labels: true
      - type: custom:mini-graph-card
        name: Температура в кімнаті
        entities:
          - sensor.temperature_158d0002437932
        line_color: var(--accent-color)
        line_width: 4
        font_size: 40
        show:
          labels: true
        color_thresholds:
          - value: 22
            color: "#f39c12"
          - value: 22.5
            color: "#d35400"
          - value: 23
            color: "#c0392b"
      - type: entity-button
        name: Виключити комп'ютер
        tap_action:
          action: call-service
          service: script.turn_on
          icon: mdi:windows
          service_data:
            entity_id: script.turn_off_pc
        entity: script.swich_pc_state
      - type: entities
        title: Вмикачі
        icon: mdi:home-assistant
        entities:
          - entity: switch.wall_switch_right_158d0001f4852b
            name: Коридор - Споти
            icon: mdi:spotlight-beam
          - entity: switch.wall_switch_right_158d0001dc2c2e
            name: Кімната - Спот
            icon: mdi:spotlight-beam
          #          - entity: switch.wall_switch_left_158d0001dc2c2e
          #            name: Кімната - Місяць
          #            icon: mdi:brightness-1
          - entity: switch.wall_switch_right_158d00016c31cf
            name: Душова - Світло
            icon: mdi:lightbulb-on
          - entity: switch.wall_switch_left_158d00016c31cf
            name: Душова - Вентиляція
            icon: mdi:fan
          - entity: switch.wall_switch_left_158d00019f6738
            name: Кухня - Споти
            icon: mdi:spotlight-beam
          - entity: switch.wall_switch_right_158d00019f6738
            name: Кухня - Бра
            icon: mdi:ceiling-light
          - entity: switch.broadlink_kitchen_ambilight
            name: Кухня - Підсвітка
            icon: mdi:led-on
          - entity: switch.broadlink_kitchen_fan
            name: Кухня - Вентиляція
            icon: mdi:fan
          - entity: switch.broadlink_pc
            name: Комп
            icon: mdi:monitor
          - entity: switch.broadlink_christmas_tree
            name: Ялинка
            icon: mdi:pine-tree
          - entity: switch.wake_on_lan
            name: wake_on_lan
      - type: picture-glance
        entities: []
        title: Вхідні двері
        camera_image:  camera.generic_camera

  ### Media  ############
  - icon: mdi:speaker-multiple
    title: Second view
    cards:
      - type: "custom:jukebox-card"
        links:
          - url: http://212.26.146.50:8000/sraka.mp3
            name: Радіо Срака 😆
          - url: http://ua.uar.net:8000/vgolos
            name: Вголос 🙀
          - url: http://94.23.40.70:8010/
            name: Metal Radio 👿
          - url: http://icepe5.infomaniak.ch/jazzblues-high.mp3
            name: Jazz Radio Blues
          - url: http://stream.radioskovoroda.com:8060/skovoroda_music
            name: Радіо Сковорода
          - url: http://listen.shoutcast.com/Classic-RockFlorida
            name: Classic-Rock Florida
          - url: http://streams.greenhost.nl:8080/jazz
            name: Concertzender Jazz
          - url: http://fs-insidejazz.fast-serv.com:8282/;stream.nsv
            name: Inside Jazz
          - url: http://stream.srg-ssr.ch/m/rsj/mp3_128
            name: Radio Swiss Jazz
          - url: http://stream.beachlatinoradio.com:8030/;?d=
            name: Beach Latino Radio
          - url: http://streams.calmradio.com/api/43/128/stream/;?d=
            name: Calm Radio
          - url: http://swr-swr1-bw.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3
            name: SWR 1

        entities:
          - media_player.kitchen
      - type: media-control
        entity: media_player.kitchen
  ### Кольори  ############
  - title: Кольори
    path: colors
    id: colors
    icon: mdi:palette
    cards:
      - type: custom:light-entity-card
        entity: light.viktoriia_lamp
        header: Лампа Віки
      - type: custom:light-entity-card
        entity: light.master_lamp
        header: Лампа Васі
      - type: custom:light-entity-card
        entity: light.window
        header: Вікно
      - type: custom:light-entity-card
        entity: light.kitchen_light
        header: Кухня
      - type: custom:light-entity-card
        entity: light.group_kitchen_yeelight
        header: Вся кухня
      - type: custom:light-entity-card
        entity: light.room_moon
        header: Місяць
  ### Погода  ############
  - title: Погода
    path: weather
    id: weather
    icon: mdi:weather-sunny
    cards:
      - type: sensor
        entity: sensor.temperature_158d0002437932
        name: Температура в квартирі
      - type: custom:weather-card
        entity: weather.dark_sky
        name: Львів
      - type: history-graph
        title: 'Історія'
        entities:
          - entity: sensor.temperature_158d0002437932
            name: Температура - Коридор
          - entity: sensor.humidity_158d0002437932
            name: Вологість - Коридор
          - entity: sensor.pressure_158d0002437932
            name: Тиск - Коридор
      - type: vertical-stack
        cards:
          - type: entities
            title: Фаза Сонця
            show_header_toggle: false
            entities:
              - sensor.nextsunset
              - sensor.nextsunrise
  - title: Система
    path: system
    id: system
    icon: mdi:harddisk
    cards:
      - type: entity-button
        name: Перезавантажити
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.hass_restart
        entity: script.hass_restart
      - type: entity-button
        name: Oновити Core config
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.reload_core_config
        entity: script.reload_core_config
      - type: entity-button
        name: Оновити автоматизиції
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.automation_reload
        entity: script.automation_reload

