- platform: group
  name: all_lights
  entities:
    - light.yeelight_master_lamp
    - light.yeelight_viktoriia_lamp
    - light.yeelight_moon
    - light.yeelight_window
    - light.yeelight_kitchen
