- platform: group
  name: lights_all
  entities:
    - light.yeelight_master_lamp
    - light.yeelight_viktoriia_lamp
    - light.yeelight_moon
    - light.yeelight_window
    - light.yeelight_kitchen
- platform: group
  name: lights_kitchen
  entities:
    - light.yeelight_master_lamp
    - light.yeelight_viktoriia_lamp
- platform: group
  name: lights_room
  entities:
    - light.yeelight_window
    - light.yeelight_kitchen
