- platform: group
  name: light_group_kitchen
  entities:
    - light.window
    - light.kitchen_light

- platform: group
  name: light_group_room
  entities:
    - light.master_lamp
    - light.viktoriia_lamp
