- platform: group
  name: light_group_kitchen
  entities:
    - light.yeelight_window
    - light.yeelight_kitchen

- platform: group
  name: light_group_room
  entities:
    - light.yeelight_viktoriia_lamp
    - light.yeelight_master_lamp
