- platform: group
  name: group_kitchen_yeelight
  entities:
    - light.window
    - light.kitchen_light

- platform: group
  name: group_room_yeelight
  entities:
    - light.master-lamp
    - light.viktoriia-lamp
