# Пточний час/дата як сенсор
- platform: time_date
  display_options:
#    - 'time'
#    - 'date'
#    - 'date_time'
#    - 'date_time_utc'
#    - 'date_time_iso'
#    - 'time_date'
#    - 'time_utc'
#    - 'beat'


- platform: template
  sensors:
    beok_temperature:
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('climate.beok', 'current_temperature') }}"
